version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  api:
    build: ./api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${API_PORT}"
    volumes:
      - ./api:/code
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_NAME=${POSTGRES_SERVICE_NAME}
    depends_on:
      - db
