# Generated by Django 3.2.15 on 2022-10-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_acquisition',
            name='bat_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='door_contact_alarm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='ems_com_fail_alarm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='ext_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='fuel_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='ge_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='gen_alarm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='main_alarm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='pbat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='pload',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='psol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='soc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='solar_logd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='spd_alarm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='totalpower',
            field=models.IntegerField(),
        ),
    ]
