# Generated by Django 3.2.15 on 2022-10-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221018_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_acquisition',
            name='fuel_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='pbat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='pload',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='psol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='soc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_acquisition',
            name='totalpower',
            field=models.FloatField(),
        ),
    ]
