# Generated by Django 3.2.15 on 2022-11-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_maintenance_maintenancedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Door_event',
        ),
    ]
