# Generated by Django 3.2.15 on 2022-12-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_data_acquisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='pass_cli1', max_length=100),
        ),
    ]
