# Generated by Django 3.2.15 on 2022-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bei',
            name='password',
            field=models.CharField(default='pass_bei1', max_length=100),
            preserve_default=False,
        ),
    ]
