# Generated by Django 3.2.15 on 2022-11-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_data_acquisition'),
        ('data_acquisition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_acquisition',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('bat_temp', models.IntegerField()),
                ('solar_logd', models.IntegerField()),
                ('spd_alarm', models.IntegerField()),
                ('gen_alarm', models.IntegerField()),
                ('totalpower', models.FloatField()),
                ('fuel_level', models.FloatField()),
                ('ext_temp', models.IntegerField()),
                ('ge_temp', models.IntegerField()),
                ('soc', models.FloatField()),
                ('main_alarm', models.IntegerField()),
                ('ems_com_fail_alarm', models.IntegerField()),
                ('door_contact_alarm', models.IntegerField()),
                ('pbat', models.FloatField()),
                ('psol', models.FloatField()),
                ('pload', models.FloatField()),
                ('bei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_acquisition', to='dashboard.bei')),
            ],
        ),
    ]
