# Generated by Django 3.2.15 on 2022-12-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_data_acquisition'),
        ('data_acquisition', '0002_data_acquisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_acquisition',
            name='bei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_acquisition_bei', to='dashboard.bei'),
        ),
    ]
